dockerversion: "3.7"

services:
  app:
    build:
      context: .
    container_name: pizza-shop-backend
    volumes:
      - ./target:/app
    restart: on-failure
    command: ["java", "-jar", "book-records-task-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - pizzaShopNetwork
  db:
    image: mysql
    container_name: pizza-database
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: book
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    restart: on-failure
    ports:
      - "3306:3306"
    networks:
      - pizzaShopNetwork
#  web:
#    build:
#      context: ./PizzaShopAngular
#      dockerfile: Dockerfile.prod
#    restart: on-failure
#    depends_on:
#      #      - db
#      - app
#    container_name: pizza-shop-frontend
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./PizzaShopAngular/dist/pizza-shop:/usr/share/nginx/html
#    ports:
#      - "80:80"
#    networks:
#      - pizzaShopNetwork
networks:
  pizzaShopNetwork:
    driver: bridge
